In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import warnings 
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import kagglehub

warnings.filterwarnings("ignore")

In [1]:
# Install kagglehub
!pip install kagglehub

import kagglehub
import pandas as pd

# Download the dataset
path = kagglehub.dataset_download("mathchi/diabetes-data-set")
print("Path to dataset files:", path)

# Load the dataset
df = pd.read_csv(path + "/diabetes.csv")
df.head()

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2026.1.4)
Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/mathchi/diabetes-data-set?dataset_version_number=1...

100%|██████████| 8.91k/8.91k [00:00<00:00, 11.7MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/mathchi/diabetes-data-set/versions/1

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
X = df.iloc[: , :-1]
y = df.iloc[: , -1]

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [7]:
X.shape

(768, 8)

In [8]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X ,y , test_size = 0.2 , random_state = 42)

In [10]:
import tensorflow as tf 
from tensorflow import keras 
from keras import Sequential 
from keras.layers import Dense

In [11]:
# Build and train the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(16, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [12]:
history = model.fit(X_train , y_train , epochs=100 , batch_size = 32 , validation_data = (X_test , y_test) , verbose = 1)

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6194 - loss: 0.6807 - val_accuracy: 0.6623 - val_loss: 0.6275
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6982 - loss: 0.5861 - val_accuracy: 0.7273 - val_loss: 0.5696
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7380 - loss: 0.5225 - val_accuracy: 0.7273 - val_loss: 0.5339
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7536 - loss: 0.5013 - val_accuracy: 0.7532 - val_loss: 0.5170
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8001 - loss: 0.4509 - val_accuracy: 0.7597 - val_loss: 0.5187
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8020 - loss: 0.4283 - val_accuracy: 0.7532 - val_loss: 0.5272
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7751 - loss: 0.4543 - val_accuracy: 0.7597 - val_loss: 0.5308
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8003 - loss: 0.4429 - val_accuracy: 0.7468 - val_loss: 0.5354
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7966 - loss: 0.4329 - val_accuracy: 0.7468 - val_loss: 0.5399
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7872 - loss: 0.4401 - val_accuracy: 0.7532 - val_loss: 0.5405
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8225 - loss: 0.4073 - val_accuracy: 0.7532 - val_loss: 0.5473
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8221 - loss: 0.3939 - val_accuracy: 0.7532 - val_loss: 0.5493
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7956 - loss: 0.4080 - val_accuracy: 0.7468 - val_loss: 0.5543
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8241 - loss: 0.3858 - val_accuracy: 0.7597 - val_loss: 0.5482
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8191 - loss: 0.3949 - val_accuracy: 0.7403 - val_loss: 0.5581
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8064 - loss: 0.4072 - val_accuracy: 0.7403 - val_loss: 0.5625
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8265 - loss: 0.3981 - val_accuracy: 0.7468 - val_loss: 0.5570
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8346 - loss: 0.3705 - val_accuracy: 0.7338 - val_loss: 0.5684
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8188 - loss: 0.3945 - val_accuracy: 0.7403 - val_loss: 0.5643
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8447 - loss: 0.3615 - val_accuracy: 0.7403 - val_loss: 0.5641
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8047 - loss: 0.3992 - val_accuracy: 0.7208 - val_loss: 0.5673
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8317 - loss: 0.3726 - val_accuracy: 0.7403 - val_loss: 0.5769
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8386 - loss: 0.3796 - val_accuracy: 0.7403 - val_loss: 0.5801
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8406 - loss: 0.3627 - val_accuracy: 0.7273 - val_loss: 0.5852
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8417 - loss: 0.3595 - val_accuracy: 0.7338 - val_loss: 0.5851
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8353 - loss: 0.3757 - val_accuracy: 0.7273 - val_loss: 0.5832
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8243 - loss: 0.3790 - val_accuracy: 0.7403 - val_loss: 0.5934
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8540 - loss: 0.3495 - val_accuracy: 0.7143 - val_loss: 0.5909
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8558 - loss: 0.3434 - val_accuracy: 0.7143 - val_loss: 0.6003
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8604 - loss: 0.3230 - val_accuracy: 0.7208 - val_loss: 0.6004
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3593 - val_accuracy: 0.7338 - val_loss: 0.6030
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8412 - loss: 0.3528 - val_accuracy: 0.7208 - val_loss: 0.6081
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8582 - loss: 0.3245 - val_accuracy: 0.7013 - val_loss: 0.6201
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8440 - loss: 0.3522 - val_accuracy: 0.7403 - val_loss: 0.6137
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8666 - loss: 0.3151 - val_accuracy: 0.7273 - val_loss: 0.6218
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8549 - loss: 0.3378 - val_accuracy: 0.7143 - val_loss: 0.6342
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8560 - loss: 0.3266 - val_accuracy: 0.7078 - val_loss: 0.6357
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8631 - loss: 0.3028 - val_accuracy: 0.7143 - val_loss: 0.6362
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8601 - loss: 0.3199 - val_accuracy: 0.7273 - val_loss: 0.6418
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8743 - loss: 0.3018 - val_accuracy: 0.7273 - val_loss: 0.6422
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8546 - loss: 0.3182 - val_accuracy: 0.7143 - val_loss: 0.6495
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8616 - loss: 0.3491 - val_accuracy: 0.7338 - val_loss: 0.6604
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8982 - loss: 0.2642 - val_accuracy: 0.7143 - val_loss: 0.6655
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8733 - loss: 0.2989 - val_accuracy: 0.7208 - val_loss: 0.6659
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8932 - loss: 0.2669 - val_accuracy: 0.7273 - val_loss: 0.6759
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8933 - loss: 0.2730 - val_accuracy: 0.7208 - val_loss: 0.6728
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8839 - loss: 0.2789 - val_accuracy: 0.7013 - val_loss: 0.6920
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8846 - loss: 0.2528 - val_accuracy: 0.7338 - val_loss: 0.6814
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8840 - loss: 0.2519 - val_accuracy: 0.7208 - val_loss: 0.6979
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9019 - loss: 0.2709 - val_accuracy: 0.7013 - val_loss: 0.6910
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8864 - loss: 0.2743 - val_accuracy: 0.7078 - val_loss: 0.7240
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8740 - loss: 0.2642 - val_accuracy: 0.7273 - val_loss: 0.7094
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8944 - loss: 0.2771 - val_accuracy: 0.7273 - val_loss: 0.7516
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8816 - loss: 0.2637 - val_accuracy: 0.7208 - val_loss: 0.7347
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9075 - loss: 0.2556 - val_accuracy: 0.7208 - val_loss: 0.7548
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8879 - loss: 0.2571 - val_accuracy: 0.7273 - val_loss: 0.7283
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9137 - loss: 0.2503 - val_accuracy: 0.7273 - val_loss: 0.7744
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8982 - loss: 0.2529 - val_accuracy: 0.7338 - val_loss: 0.7545
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9215 - loss: 0.2268 - val_accuracy: 0.7273 - val_loss: 0.7696
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9152 - loss: 0.2358 - val_accuracy: 0.7078 - val_loss: 0.7862
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8797 - loss: 0.2691 - val_accuracy: 0.7338 - val_loss: 0.7769
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9114 - loss: 0.2475 - val_accuracy: 0.7208 - val_loss: 0.7869
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9273 - loss: 0.2209 - val_accuracy: 0.7403 - val_loss: 0.7973
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9340 - loss: 0.2016 - val_accuracy: 0.6948 - val_loss: 0.8151
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8986 - loss: 0.2485 - val_accuracy: 0.7273 - val_loss: 0.8353
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9107 - loss: 0.2432 - val_accuracy: 0.7208 - val_loss: 0.8220
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9246 - loss: 0.2100 - val_accuracy: 0.7208 - val_loss: 0.8425
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9184 - loss: 0.1981 - val_accuracy: 0.7273 - val_loss: 0.8424
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9377 - loss: 0.1945 - val_accuracy: 0.7143 - val_loss: 0.8647
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9224 - loss: 0.1977 - val_accuracy: 0.7013 - val_loss: 0.8696
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9220 - loss: 0.2188 - val_accuracy: 0.7143 - val_loss: 0.8777
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9318 - loss: 0.1845 - val_accuracy: 0.7273 - val_loss: 0.8805
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9305 - loss: 0.2090 - val_accuracy: 0.7143 - val_loss: 0.8718
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9419 - loss: 0.1883 - val_accuracy: 0.7143 - val_loss: 0.8827
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9292 - loss: 0.1938 - val_accuracy: 0.7208 - val_loss: 0.9061
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9414 - loss: 0.1765 - val_accuracy: 0.7208 - val_loss: 0.9267
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9374 - loss: 0.1839 - val_accuracy: 0.7208 - val_loss: 0.9115
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9494 - loss: 0.1764 - val_accuracy: 0.7143 - val_loss: 0.9360
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9433 - loss: 0.1774 - val_accuracy: 0.7273 - val_loss: 0.9351
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9512 - loss: 0.1908 - val_accuracy: 0.7013 - val_loss: 0.9452
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9462 - loss: 0.1800 - val_accuracy: 0.7078 - val_loss: 0.9787
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9475 - loss: 0.1625 - val_accuracy: 0.7078 - val_loss: 0.9607
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9444 - loss: 0.1631 - val_accuracy: 0.7208 - val_loss: 0.9746
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9508 - loss: 0.1549 - val_accuracy: 0.7208 - val_loss: 0.9811
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9586 - loss: 0.1401 - val_accuracy: 0.7143 - val_loss: 0.9847
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9571 - loss: 0.1422 - val_accuracy: 0.7273 - val_loss: 0.9992
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9429 - loss: 0.1718 - val_accuracy: 0.7338 - val_loss: 1.0095
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9592 - loss: 0.1611 - val_accuracy: 0.7143 - val_loss: 1.0331
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9759 - loss: 0.1348 - val_accuracy: 0.7338 - val_loss: 1.0208
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9595 - loss: 0.1385 - val_accuracy: 0.7208 - val_loss: 1.0304
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9651 - loss: 0.1320 - val_accuracy: 0.7013 - val_loss: 1.0456
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9627 - loss: 0.1232 - val_accuracy: 0.7338 - val_loss: 1.0647
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9594 - loss: 0.1462 - val_accuracy: 0.7078 - val_loss: 1.0798
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9730 - loss: 0.1181 - val_accuracy: 0.7273 - val_loss: 1.0679
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9679 - loss: 0.1260 - val_accuracy: 0.7013 - val_loss: 1.0652
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9658 - loss: 0.1407 - val_accuracy: 0.7078 - val_loss: 1.1053
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9684 - loss: 0.1350 - val_accuracy: 0.7078 - val_loss: 1.0897
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9717 - loss: 0.1272 - val_accuracy: 0.7013 - val_loss: 1.1234
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9567 - loss: 0.1484 - val_accuracy: 0.7078 - val_loss: 1.1231
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9794 - loss: 0.1137 - val_accuracy: 0.7273 - val_loss: 1.1256

In [13]:
# now using the keras tuner for hyperparameter tuning 
# how to select the appropriate optimizer , nodes in a layers , number of hidden layers ,
# end me all in one

In [16]:
!pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.78.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.15.1)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.18.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.1.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 4.0 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [18]:
import kerastuner as kt

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

def build_model(hp):
    model = Sequential([
        Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
        Dense(32, activation='relu'),
        Dense(16, activation='relu'),
        Dense(1, activation='sigmoid')
    ])

    model.compile(
        optimizer=hp.Choice(
            'optimizer',
            values=['adam', 'sgd', 'rmsprop', 'adadelta']
        ),
        loss='binary_crossentropy',
        metrics=['accuracy']
    )

    return model

In [24]:
tuner = kt.RandomSearch(build_model , 
                        objective = 'val_accuracy' , 
                        max_trials = 5)
tuner.search(X_train , y_train , epochs = 5 , validation_data = (X_test , y_test), verbose = 3)

Reloading Tuner from ./untitled_project/tuner0.json

In [26]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [27]:
req_model = tuner.get_best_models(num_models=1)[0]
req_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,201 (12.50 KB)

 Trainable params: 3,201 (12.50 KB)

 Non-trainable params: 0 (0.00 B)

In [30]:
req_model.fit(X_train , y_train , batch_size =32 , verbose = 1 , epochs = 100 , initial_epoch= 6 , validation_data = (X_test , y_test) )

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7704 - loss: 0.4819 - val_accuracy: 0.7662 - val_loss: 0.4938
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7927 - loss: 0.4264 - val_accuracy: 0.7597 - val_loss: 0.4961
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7672 - loss: 0.4501 - val_accuracy: 0.7727 - val_loss: 0.5018
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7636 - loss: 0.4555 - val_accuracy: 0.7662 - val_loss: 0.4986
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7945 - loss: 0.4203 - val_accuracy: 0.7662 - val_loss: 0.4961
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7922 - loss: 0.4569 - val_accuracy: 0.7468 - val_loss: 0.5000
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7823 - loss: 0.4342 - val_accuracy: 0.7792 - val_loss: 0.4977
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7983 - loss: 0.4111 - val_accuracy: 0.7532 - val_loss: 0.4980
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8081 - loss: 0.4072 - val_accuracy: 0.7662 - val_loss: 0.5007
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4072 - val_accuracy: 0.7597 - val_loss: 0.5041
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7826 - loss: 0.4343 - val_accuracy: 0.7532 - val_loss: 0.5060
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8051 - loss: 0.3995 - val_accuracy: 0.7597 - val_loss: 0.5112
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8115 - loss: 0.4082 - val_accuracy: 0.7532 - val_loss: 0.5169
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8174 - loss: 0.4113 - val_accuracy: 0.7597 - val_loss: 0.5179
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7989 - loss: 0.4388 - val_accuracy: 0.7532 - val_loss: 0.5178
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7895 - loss: 0.3970 - val_accuracy: 0.7792 - val_loss: 0.5177
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8119 - loss: 0.4121 - val_accuracy: 0.7727 - val_loss: 0.5203
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8080 - loss: 0.3995 - val_accuracy: 0.7532 - val_loss: 0.5254
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8352 - loss: 0.3766 - val_accuracy: 0.7662 - val_loss: 0.5306
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8001 - loss: 0.4021 - val_accuracy: 0.7403 - val_loss: 0.5364
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7948 - loss: 0.4152 - val_accuracy: 0.7532 - val_loss: 0.5336
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8140 - loss: 0.3829 - val_accuracy: 0.7597 - val_loss: 0.5319
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8001 - loss: 0.4087 - val_accuracy: 0.7597 - val_loss: 0.5360
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8338 - loss: 0.3857 - val_accuracy: 0.7597 - val_loss: 0.5329
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8167 - loss: 0.3830 - val_accuracy: 0.7532 - val_loss: 0.5361
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8397 - loss: 0.3801 - val_accuracy: 0.7727 - val_loss: 0.5360
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8206 - loss: 0.3670 - val_accuracy: 0.7597 - val_loss: 0.5428
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8318 - loss: 0.3549 - val_accuracy: 0.7662 - val_loss: 0.5434
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8103 - loss: 0.3785 - val_accuracy: 0.7597 - val_loss: 0.5512
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8270 - loss: 0.3693 - val_accuracy: 0.7662 - val_loss: 0.5460
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8169 - loss: 0.3744 - val_accuracy: 0.7468 - val_loss: 0.5486
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8227 - loss: 0.3494 - val_accuracy: 0.7468 - val_loss: 0.5578
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8167 - loss: 0.3857 - val_accuracy: 0.7662 - val_loss: 0.5556
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8217 - loss: 0.3559 - val_accuracy: 0.7273 - val_loss: 0.5642
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8685 - loss: 0.3242 - val_accuracy: 0.7532 - val_loss: 0.5619
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8258 - loss: 0.3668 - val_accuracy: 0.7468 - val_loss: 0.5658
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8142 - loss: 0.3904 - val_accuracy: 0.7532 - val_loss: 0.5634
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8628 - loss: 0.3499 - val_accuracy: 0.7532 - val_loss: 0.5705
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8466 - loss: 0.3530 - val_accuracy: 0.7338 - val_loss: 0.5652
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8390 - loss: 0.3380 - val_accuracy: 0.7273 - val_loss: 0.5698
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8250 - loss: 0.3717 - val_accuracy: 0.7403 - val_loss: 0.5708
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8662 - loss: 0.3219 - val_accuracy: 0.7273 - val_loss: 0.5730
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8527 - loss: 0.3540 - val_accuracy: 0.7338 - val_loss: 0.5790
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8483 - loss: 0.3400 - val_accuracy: 0.7403 - val_loss: 0.5775
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8750 - loss: 0.3036 - val_accuracy: 0.7403 - val_loss: 0.5709
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8536 - loss: 0.3445 - val_accuracy: 0.7273 - val_loss: 0.5849
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8381 - loss: 0.3813 - val_accuracy: 0.7468 - val_loss: 0.5813
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8460 - loss: 0.3272 - val_accuracy: 0.7403 - val_loss: 0.5773
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8596 - loss: 0.3450 - val_accuracy: 0.7338 - val_loss: 0.5865
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8747 - loss: 0.3009 - val_accuracy: 0.7468 - val_loss: 0.5935
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8764 - loss: 0.3225 - val_accuracy: 0.7273 - val_loss: 0.6038
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8597 - loss: 0.3367 - val_accuracy: 0.7143 - val_loss: 0.6092
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8608 - loss: 0.3168 - val_accuracy: 0.7208 - val_loss: 0.5993
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8641 - loss: 0.3306 - val_accuracy: 0.7338 - val_loss: 0.6011
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8503 - loss: 0.3424 - val_accuracy: 0.7078 - val_loss: 0.6112
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8592 - loss: 0.3547 - val_accuracy: 0.7338 - val_loss: 0.6165
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8817 - loss: 0.2996 - val_accuracy: 0.7273 - val_loss: 0.6090
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8819 - loss: 0.3026 - val_accuracy: 0.7403 - val_loss: 0.6109
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8598 - loss: 0.3321 - val_accuracy: 0.7403 - val_loss: 0.6136
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8441 - loss: 0.3506 - val_accuracy: 0.7403 - val_loss: 0.6255
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8616 - loss: 0.3258 - val_accuracy: 0.7338 - val_loss: 0.6212
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8683 - loss: 0.3208 - val_accuracy: 0.7403 - val_loss: 0.6255
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8789 - loss: 0.3094 - val_accuracy: 0.7208 - val_loss: 0.6454
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8673 - loss: 0.3048 - val_accuracy: 0.7468 - val_loss: 0.6362
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8977 - loss: 0.2846 - val_accuracy: 0.7208 - val_loss: 0.6406
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8671 - loss: 0.3291 - val_accuracy: 0.7338 - val_loss: 0.6419
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8509 - loss: 0.3428 - val_accuracy: 0.7403 - val_loss: 0.6467
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8863 - loss: 0.2858 - val_accuracy: 0.7403 - val_loss: 0.6495
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8686 - loss: 0.3098 - val_accuracy: 0.7273 - val_loss: 0.6555
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8914 - loss: 0.2770 - val_accuracy: 0.7403 - val_loss: 0.6579
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8740 - loss: 0.2956 - val_accuracy: 0.7403 - val_loss: 0.6520
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8957 - loss: 0.2731 - val_accuracy: 0.7338 - val_loss: 0.6541
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8786 - loss: 0.2837 - val_accuracy: 0.7143 - val_loss: 0.6684
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8994 - loss: 0.2642 - val_accuracy: 0.7338 - val_loss: 0.6862
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8782 - loss: 0.3035 - val_accuracy: 0.7273 - val_loss: 0.6853
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9034 - loss: 0.2501 - val_accuracy: 0.7143 - val_loss: 0.6700
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8843 - loss: 0.2813 - val_accuracy: 0.7273 - val_loss: 0.6947
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8675 - loss: 0.2849 - val_accuracy: 0.7273 - val_loss: 0.6891
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8864 - loss: 0.2693 - val_accuracy: 0.7013 - val_loss: 0.6948
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8949 - loss: 0.2677 - val_accuracy: 0.7273 - val_loss: 0.7124
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8935 - loss: 0.2593 - val_accuracy: 0.7338 - val_loss: 0.7129
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9027 - loss: 0.2499 - val_accuracy: 0.7273 - val_loss: 0.7221
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9021 - loss: 0.2495 - val_accuracy: 0.7273 - val_loss: 0.7212
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8846 - loss: 0.2675 - val_accuracy: 0.7143 - val_loss: 0.7536
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9021 - loss: 0.2645 - val_accuracy: 0.6948 - val_loss: 0.7371
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8929 - loss: 0.2400 - val_accuracy: 0.7013 - val_loss: 0.7465
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8826 - loss: 0.2660 - val_accuracy: 0.7208 - val_loss: 0.7495
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9057 - loss: 0.2333 - val_accuracy: 0.7338 - val_loss: 0.7302
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8858 - loss: 0.2790 - val_accuracy: 0.7078 - val_loss: 0.7628
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8954 - loss: 0.2776 - val_accuracy: 0.7273 - val_loss: 0.7532
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8957 - loss: 0.2378 - val_accuracy: 0.6948 - val_loss: 0.7692
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8959 - loss: 0.2382 - val_accuracy: 0.7208 - val_loss: 0.7472
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9172 - loss: 0.2268 - val_accuracy: 0.7338 - val_loss: 0.7609
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8897 - loss: 0.2435 - val_accuracy: 0.7143 - val_loss: 0.7736

In [31]:
def build_model(hp):
    model = Sequential()
    units = hp.Int(8 , 128 , step = 8)
    # takes the nodes in the nn layers as 8 , 16 , 24 , 32, 40 ,.....128
    model.add(Dense(units = units , activation = 'relu' , input_dim = 8))
    model.add(Dense(units = units , activation = 'relu'))
    model.add(Dense(units = units , activation = 'relu'))
    model.add(Dense(units = units , activation = 'relu'))
    model.add(Dense(1 ,activation = 'sigmoid'))

    model.compile(optimizers = 'rmsprop' , loss = 'binary_crossentropy' , metrics = ['accuracy'])

    return model

In [32]:
tuner = kt.RandomSearch(build_model , objective= 'val_acc' , max_trials = 10)

Reloading Tuner from ./untitled_project/tuner0.json

In [34]:
tuner.search(X_train , y_train , validation_data = (X_test , y_test ) , epochs = 5 )

In [35]:
# best output 
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [37]:
model.fit(X_train , y_train , batch_size = 32, epochs =100 , validation_data = (X_test , y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9802 - loss: 0.0979 - val_accuracy: 0.6948 - val_loss: 1.1465
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9699 - loss: 0.1169 - val_accuracy: 0.7078 - val_loss: 1.1479
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9798 - loss: 0.1110 - val_accuracy: 0.7013 - val_loss: 1.1731
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9749 - loss: 0.1062 - val_accuracy: 0.7078 - val_loss: 1.1693
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9768 - loss: 0.1137 - val_accuracy: 0.6948 - val_loss: 1.1848
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9664 - loss: 0.1173 - val_accuracy: 0.7143 - val_loss: 1.1896
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9849 - loss: 0.0923 - val_accuracy: 0.6883 - val_loss: 1.2104
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9763 - loss: 0.1021 - val_accuracy: 0.6818 - val_loss: 1.2439
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9851 - loss: 0.0969 - val_accuracy: 0.7013 - val_loss: 1.2402
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9845 - loss: 0.0864 - val_accuracy: 0.7078 - val_loss: 1.2497
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9838 - loss: 0.0941 - val_accuracy: 0.7143 - val_loss: 1.2657
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9820 - loss: 0.0914 - val_accuracy: 0.7273 - val_loss: 1.2843
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9768 - loss: 0.1004 - val_accuracy: 0.7013 - val_loss: 1.3550
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9843 - loss: 0.0858 - val_accuracy: 0.7208 - val_loss: 1.3193
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9783 - loss: 0.0974 - val_accuracy: 0.6753 - val_loss: 1.3077
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9851 - loss: 0.0856 - val_accuracy: 0.6818 - val_loss: 1.2715
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0876 - val_accuracy: 0.7013 - val_loss: 1.3334
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9807 - loss: 0.0890 - val_accuracy: 0.7013 - val_loss: 1.3132
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9880 - loss: 0.0856 - val_accuracy: 0.6883 - val_loss: 1.3334
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9898 - loss: 0.0683 - val_accuracy: 0.6753 - val_loss: 1.3441
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9825 - loss: 0.0747 - val_accuracy: 0.6948 - val_loss: 1.3573
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9834 - loss: 0.0763 - val_accuracy: 0.6818 - val_loss: 1.3799
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9897 - loss: 0.0666 - val_accuracy: 0.6948 - val_loss: 1.3944
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9874 - loss: 0.0633 - val_accuracy: 0.6883 - val_loss: 1.3770
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9800 - loss: 0.0801 - val_accuracy: 0.6818 - val_loss: 1.4234
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9842 - loss: 0.0680 - val_accuracy: 0.6753 - val_loss: 1.4465
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9848 - loss: 0.0659 - val_accuracy: 0.6948 - val_loss: 1.3944
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9909 - loss: 0.0585 - val_accuracy: 0.6948 - val_loss: 1.4109
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9935 - loss: 0.0566 - val_accuracy: 0.6883 - val_loss: 1.4638
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9903 - loss: 0.0591 - val_accuracy: 0.7013 - val_loss: 1.4677
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9834 - loss: 0.0564 - val_accuracy: 0.6883 - val_loss: 1.5166
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9857 - loss: 0.0619 - val_accuracy: 0.6818 - val_loss: 1.5007
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9891 - loss: 0.0612 - val_accuracy: 0.6818 - val_loss: 1.5282
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9833 - loss: 0.0596 - val_accuracy: 0.6948 - val_loss: 1.5125
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9857 - loss: 0.0596 - val_accuracy: 0.6818 - val_loss: 1.5356
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9870 - loss: 0.0513 - val_accuracy: 0.6883 - val_loss: 1.5325
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9889 - loss: 0.0527 - val_accuracy: 0.6948 - val_loss: 1.5578
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9858 - loss: 0.0597 - val_accuracy: 0.6883 - val_loss: 1.5200
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9858 - loss: 0.0691 - val_accuracy: 0.6883 - val_loss: 1.6379
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9822 - loss: 0.0663 - val_accuracy: 0.6883 - val_loss: 1.5417
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9838 - loss: 0.0736 - val_accuracy: 0.6883 - val_loss: 1.6247
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9830 - loss: 0.0544 - val_accuracy: 0.6883 - val_loss: 1.6219
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9817 - loss: 0.0595 - val_accuracy: 0.6688 - val_loss: 1.6869
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9907 - loss: 0.0504 - val_accuracy: 0.6883 - val_loss: 1.6219
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9908 - loss: 0.0414 - val_accuracy: 0.6818 - val_loss: 1.6196
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9915 - loss: 0.0410 - val_accuracy: 0.6948 - val_loss: 1.6430
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9895 - loss: 0.0517 - val_accuracy: 0.7078 - val_loss: 1.6777
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9910 - loss: 0.0554 - val_accuracy: 0.7013 - val_loss: 1.6856
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9854 - loss: 0.0563 - val_accuracy: 0.6818 - val_loss: 1.6834
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9906 - loss: 0.0387 - val_accuracy: 0.6883 - val_loss: 1.6687
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9968 - loss: 0.0384 - val_accuracy: 0.6883 - val_loss: 1.7027
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9957 - loss: 0.0377 - val_accuracy: 0.6883 - val_loss: 1.7258
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9961 - loss: 0.0362 - val_accuracy: 0.6818 - val_loss: 1.7513
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9910 - loss: 0.0339 - val_accuracy: 0.6753 - val_loss: 1.7345
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9982 - loss: 0.0276 - val_accuracy: 0.6883 - val_loss: 1.7411
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9926 - loss: 0.0359 - val_accuracy: 0.6948 - val_loss: 1.7846
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9894 - loss: 0.0324 - val_accuracy: 0.6948 - val_loss: 1.7457
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9956 - loss: 0.0326 - val_accuracy: 0.6948 - val_loss: 1.7928
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9949 - loss: 0.0313 - val_accuracy: 0.7013 - val_loss: 1.7688
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9959 - loss: 0.0327 - val_accuracy: 0.6883 - val_loss: 1.8156
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9971 - loss: 0.0313 - val_accuracy: 0.6818 - val_loss: 1.8549
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9871 - loss: 0.0340 - val_accuracy: 0.7013 - val_loss: 1.8752
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9860 - loss: 0.0393 - val_accuracy: 0.6818 - val_loss: 1.8261
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9954 - loss: 0.0434 - val_accuracy: 0.6948 - val_loss: 1.8840
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9890 - loss: 0.0445 - val_accuracy: 0.6818 - val_loss: 1.8572
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9991 - loss: 0.0308 - val_accuracy: 0.6948 - val_loss: 1.8673
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9960 - loss: 0.0214 - val_accuracy: 0.6948 - val_loss: 1.8600
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0243 - val_accuracy: 0.6948 - val_loss: 1.9003
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9982 - loss: 0.0216 - val_accuracy: 0.6948 - val_loss: 1.9194
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9991 - loss: 0.0243 - val_accuracy: 0.7078 - val_loss: 1.9326
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9929 - loss: 0.0256 - val_accuracy: 0.6753 - val_loss: 1.9782
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9953 - loss: 0.0221 - val_accuracy: 0.6948 - val_loss: 1.9162
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9989 - loss: 0.0194 - val_accuracy: 0.6948 - val_loss: 1.9641
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9997 - loss: 0.0197 - val_accuracy: 0.6818 - val_loss: 2.0027
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0177 - val_accuracy: 0.6948 - val_loss: 1.9685
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0181 - val_accuracy: 0.6883 - val_loss: 1.9991
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9982 - loss: 0.0208 - val_accuracy: 0.6818 - val_loss: 2.0084
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0203 - val_accuracy: 0.6883 - val_loss: 2.0332
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9995 - loss: 0.0173 - val_accuracy: 0.6883 - val_loss: 2.0628
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0202 - val_accuracy: 0.7013 - val_loss: 2.0500
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9988 - loss: 0.0223 - val_accuracy: 0.6688 - val_loss: 2.0729
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9968 - loss: 0.0192 - val_accuracy: 0.6883 - val_loss: 2.0652
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9982 - loss: 0.0209 - val_accuracy: 0.7013 - val_loss: 2.0413
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9973 - loss: 0.0171 - val_accuracy: 0.6818 - val_loss: 2.1219
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9952 - loss: 0.0197 - val_accuracy: 0.6818 - val_loss: 2.0634
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9994 - loss: 0.0172 - val_accuracy: 0.6948 - val_loss: 2.1078
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0153 - val_accuracy: 0.7013 - val_loss: 2.1336
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0138 - val_accuracy: 0.6948 - val_loss: 2.1335
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 1.0000 - loss: 0.0119 - val_accuracy: 0.6948 - val_loss: 2.1562
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0149 - val_accuracy: 0.6883 - val_loss: 2.1722
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0148 - val_accuracy: 0.6818 - val_loss: 2.2246
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 1.0000 - loss: 0.0133 - val_accuracy: 0.6948 - val_loss: 2.1821
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.9995 - loss: 0.0159 - val_accuracy: 0.6753 - val_loss: 2.3094
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0209 - val_accuracy: 0.6883 - val_loss: 2.2263
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0105 - val_accuracy: 0.6818 - val_loss: 2.2333
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 1.0000 - loss: 0.0128 - val_accuracy: 0.6688 - val_loss: 2.2576
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0124 - val_accuracy: 0.6948 - val_loss: 2.2279
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0121 - val_accuracy: 0.6948 - val_loss: 2.2537
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 1.0000 - loss: 0.0106 - val_accuracy: 0.6883 - val_loss: 2.2515
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9997 - loss: 0.0165 - val_accuracy: 0.6818 - val_loss: 2.3184

In [48]:
from sklearn import metrics


def build_model(hp):
    model = Sequential()
    model.add(Dense(72 , activation = 'relu' ))
    for i in range(hp.Int('num_layers' , min_value=1 , max_value = 10)):


        model.add(Dense(72, activation = 'relu' ))
        model.add(Dense(1 , activation = 'sigmoid'))

        model.compile(optimizer = 'rmsprop' , loss = 'binary_crossentropy' , metrics =['accuracy'])

    return model

In [49]:
tuner = kt.RandomSearch(build_model , objective = 'val_loss' , max_trials = 3 , 
                        directory = 'my_dir' , project_name = 'Sallu_bhai')

Reloading Tuner from my_dir/Sallu_bhai/tuner0.json

In [50]:
tuner.search(X_train , y_train ,epochs= 5 , validation_data =(X_test , y_test) , verbose = 1)

Trial 3 Complete [00h 00m 05s]
val_loss: 0.6517665386199951

Best val_loss So Far: 0.6517665386199951
Total elapsed time: 00h 00m 37s

In [51]:
model = tuner.get_best_models(num_models = 1)[0]

In [53]:
model.fit(X_train , y_train , epochs = 100 , initial_epoch = 6 , validation_data = (X_test , y_test ))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 16ms/step - accuracy: 0.6398 - loss: 0.6546 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6536 - loss: 0.6456 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6458 - loss: 0.6504 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6014 - loss: 0.6771 - val_accuracy: 0.6429 - val_loss: 0.6524
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6343 - loss: 0.6582 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6350 - loss: 0.6577 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6484 - loss: 0.6487 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6609 - loss: 0.6411 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6571 - loss: 0.6435 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6511 - loss: 0.6470 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6715 - loss: 0.6343 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6732 - loss: 0.6328 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6332 - loss: 0.6581 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6473 - loss: 0.6494 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6545 - loss: 0.6450 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6498 - loss: 0.6479 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6565 - loss: 0.6437 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6622 - loss: 0.6399 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6360 - loss: 0.6570 - val_accuracy: 0.6429 - val_loss: 0.6524
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6590 - loss: 0.6421 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6730 - loss: 0.6327 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6930 - loss: 0.6196 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6588 - loss: 0.6425 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6815 - loss: 0.6287 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6301 - loss: 0.6594 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6465 - loss: 0.6498 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6470 - loss: 0.6496 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6850 - loss: 0.6248 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6772 - loss: 0.6311 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6887 - loss: 0.6239 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6651 - loss: 0.6385 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6445 - loss: 0.6513 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6814 - loss: 0.6274 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6643 - loss: 0.6386 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6701 - loss: 0.6355 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6684 - loss: 0.6370 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6807 - loss: 0.6300 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6598 - loss: 0.6421 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6812 - loss: 0.6278 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6341 - loss: 0.6575 - val_accuracy: 0.6429 - val_loss: 0.6523
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6655 - loss: 0.6376 - val_accuracy: 0.6429 - val_loss: 0.6524
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6458 - loss: 0.6507 - val_accuracy: 0.6429 - val_loss: 0.6525
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6610 - loss: 0.6406 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6558 - loss: 0.6441 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6515 - loss: 0.6471 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6809 - loss: 0.6280 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6581 - loss: 0.6427 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6366 - loss: 0.6561 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6294 - loss: 0.6611 - val_accuracy: 0.6429 - val_loss: 0.6523
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.6452 - loss: 0.6509 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.6549 - loss: 0.6447 - val_accuracy: 0.6429 - val_loss: 0.6523
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6358 - loss: 0.6573 - val_accuracy: 0.6429 - val_loss: 0.6525
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6298 - loss: 0.6614 - val_accuracy: 0.6429 - val_loss: 0.6528
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6723 - loss: 0.6329 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6539 - loss: 0.6452 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6602 - loss: 0.6412 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6340 - loss: 0.6581 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6471 - loss: 0.6497 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6528 - loss: 0.6460 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6824 - loss: 0.6274 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6334 - loss: 0.6582 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6527 - loss: 0.6462 - val_accuracy: 0.6429 - val_loss: 0.6523
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6615 - loss: 0.6404 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6441 - loss: 0.6520 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6650 - loss: 0.6381 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6291 - loss: 0.6611 - val_accuracy: 0.6429 - val_loss: 0.6523
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6304 - loss: 0.6605 - val_accuracy: 0.6429 - val_loss: 0.6527
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6543 - loss: 0.6451 - val_accuracy: 0.6429 - val_loss: 0.6523
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6634 - loss: 0.6390 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6786 - loss: 0.6292 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6587 - loss: 0.6423 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6767 - loss: 0.6316 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6477 - loss: 0.6491 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6651 - loss: 0.6378 - val_accuracy: 0.6429 - val_loss: 0.6524
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6683 - loss: 0.6358 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6353 - loss: 0.6570 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6637 - loss: 0.6389 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6487 - loss: 0.6487 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6506 - loss: 0.6476 - val_accuracy: 0.6429 - val_loss: 0.6526
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6547 - loss: 0.6448 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6533 - loss: 0.6458 - val_accuracy: 0.6429 - val_loss: 0.6523
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6490 - loss: 0.6484 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6610 - loss: 0.6408 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6659 - loss: 0.6377 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6660 - loss: 0.6374 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6634 - loss: 0.6396 - val_accuracy: 0.6429 - val_loss: 0.6520
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.6442 - loss: 0.6515 - val_accuracy: 0.6429 - val_loss: 0.6521
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.6584 - loss: 0.6423 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6404 - loss: 0.6535 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6723 - loss: 0.6339 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6317 - loss: 0.6585 - val_accuracy: 0.6429 - val_loss: 0.6519
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6267 - loss: 0.6620 - val_accuracy: 0.6429 - val_loss: 0.6522
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6659 - loss: 0.6374 - val_accuracy: 0.6429 - val_loss: 0.6518
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6530 - loss: 0.6458 - val_accuracy: 0.6429 - val_loss: 0.6518

In [60]:
def build_model_final(hp):
    model = Sequential()

    counter = 0
    
    for i in range(hp.Int('num_layers' ,  min_value = 1 , max_value = 10)):

        if counter == 0:

            model.add(Dense(hp.Int('units' + str(i) , min_value = 8 , max_value = 8) , activation = hp.Choice('activation' + str(i) , values = ['relu' , 'tanh' , 'sigmoid'])))

            model.add(Dense(1 , activation = 'sigmoid'))

        else:
            model.add(Dense(hp.Int('units' + str(i) , min_value= 8 , max_value = 8) , activation = hp.Choice('activation' + str(i) , values = ['relu' , 'tanh' , 'sigmoid'])))
            counter+=1
            
        model.compile(optimizer = hp.Choice('optimizer' , values = ['rmsprop' , 'adam' , 'sgd' , 'adadelta']))

In [61]:
tuner = kt.RandomSearch(build_model_final , objective = 'val_accuracy' , max_trials = 5)

Reloading Tuner from ./untitled_project/tuner0.json

In [ ]:
model = tuner.get_best_models(num_models=1)[0]

FatalTypeError: Expected the model-building function, or HyperModel.build() to return a valid Keras Model instance. Received: None of type <class 'NoneType'>.